### ISSUE TITLE
Invalid Entity Errors on HTML5 

### ISSUE THREAD

**Issue by feelsickened** [soundasleep/html2text#10]
I'm getting various invalid entity errors when using on what I 'think' are HTML5 pages.

Example:
Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag header invalid in Entity, 

Example HTML -> pick any page on www.independent.ie

This may be similar/related to the same issues happening here with the DOM document: http://stackoverflow.com/questions/6090667/php-domdocument-errors-warnings-on-html5-tags

This is a fantastic HTML2TEXT converter. A huge thanks and congratulations to the dev. I hope there's a work around better than turning off errors for this issue.

Cheers.

**Comment by randycoder** [comment]
How about HTML5 elements like "nav" and "section"? Is there a way to avoid "invalid in Entity" errors for those tags using DOMDocument::loadHTML()? The issue is closed but the solution is not clear.

**Comment by eazrael** [comment]
Just ran into this, too. My workaround is using HTMLPurifier + HTML5Purifier and remove the html5 tags before using html2text. Unfortunately HTMLPurifier is dead slow.

**Comment by eazrael** [comment]
And for reference: 
https://bugs.php.net/bug.php?id=60021 -> https://bugzilla.gnome.org/show_bug.cgi?id=761534
