### ISSUE TITLE
mb_convert_encoding is DEPRECATED in php 8.2

### ISSUE THREAD

**Issue by mhdhamouday** [soundasleep/html2text#102]
I have php 8.2 and I get this error when i call convert function:
E_DEPRECATED: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /composer/vendor/soundasleep/html2text/src/Html2Text.php on line 54

**Comment by edgrosvenor** [comment]
@mhdhamouday I just created a release that adds PHP 8.2 support that should resolve this. Please update to the latest version and let me know if the issue persists. I'll close this issue because I assume it's resolved but if it's not, feel free to reopen.

**Comment by mhdhamouday** [comment]
Now it's working! Thank you very much!
