### ISSUE TITLE
&nbsp; becomes Ã

### ISSUE THREAD

**Issue by brenton-vidcorp** [soundasleep/html2text#17]
As in the heading, &nbsp; becomes Ã

Can easily be fixed with:
```
$cleaner = str_replace('&nbsp;', ' ', $inHTML);
$outText = convert_html_to_text($cleaner);
```

Not sure if any other characters like that arn't handled correctly - I wish I had time to test more and provide a pull request.

**Comment by soundasleep** [comment]
It sounds like this is an encoding issue - &nbsp; should become alt-0160 which I think in some character sets is rendered as Ã. Try loading the HTML under a different encoding instead?

Will add a test case anyway to check

**Comment by soundasleep** [comment]
Have fixed.
