### ISSUE TITLE
Changes to static functions

### ISSUE THREAD

**Issue by feelsickened** [soundasleep/html2text#20]
Hi There,
Was using this great script in a function and came looking to see if it had been updated - seems quite allot of changes. However the changes to static functions seem to break for my scenario.

I am a hobbyist / old-school php guy - so any guidance or pointers would be greatly appreciated - the old html2text.php file as a standalone effort as brilliant and worked very well.

I am getting the following errors:

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag time invalid in Entity, line: 307 in  /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: ID makeComment already defined in Entity, line: 391 in  /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag section invalid in Entity, line: 560 in /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag header invalid in Entity, line: 560 in /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag article invalid in Entity, line: 563 in /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag article invalid in Entity, line: 576 in /----->/src/Html2Text.php on line 40 on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag article invalid in Entity, line: 589 in /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag article invalid in Entity, line: 601 in /----->/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Tag article invalid in Entity, line: 613 in /----->/src/Html2Text.php on line 40

**Comment by soundasleep** [comment]
It sounds like it's loading a different DTD (XHTML instead of HTML5 or something) or encoding. Could you post the HTML file you're trying to translate? Perhaps you can try minimise the HTML file to the smallest file that creates these errors?

**Comment by feelsickened** [comment]
Thanks for the prompt response - The HTML was from this article: http://www.smh.com.au/digital-life/computers/gadgets-on-the-go/getflix-offers-the-best-of-both-worlds-20150406-1mf3aa.html
What I did encoding wise - and what I did before putting that article into HTML2TEXT - I'll shed light on momentarily for you.

**Comment by feelsickened** [comment]
Very sorry for delay in providing proper issue details to you.

I am running the following:
$article_URL = (example provided above) http://www.smh.com.au/digital-life/computers/gadgets-on-the-go/getflix-offers-the-best-of-both-worlds-20150406-1mf3aa.html
$webpage_html_object = new DOMDocument();
$webpage_html_object->loadHTMLFile($article_URL);
$body = $webpage_html_object->getElementsByTagName('body');
			if ( $body && 0<$body->length ) {
  			  		$body = $body->item(0);
   				 	$webpage_body_html_string = $webpage_html_object->savehtml();
                        }
Then:
$as_plaintext = convert_html_to_text($webpage_body_html_string);

At one time I used, but have since commented out this line in preference of the above: 
$webpage_body_html_string = $webpage_html_object->savehtml($body);

**Comment by soundasleep** [comment]
It looks like the HTML is invalid, so similar to issue #10. Maybe we can look at adding an option to ignore invalid HTML warnings...

What happens if you parse the HTML directly?

```php
$as_plaintext = convert_html_to_text(file_get_contents("http://www.smh.com.au/digital-life/computers/gadgets-on-the-go/getflix-offers-the-best-of-both-worlds-20150406-1mf3aa.html"));
```

**Comment by feelsickened** [comment]
okay trying that returns more issues:
Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 151 in /home/content/20/10935220/html/engineroom/assets/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 154 in /home/content/20/10935220/html/engineroom/assets/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 157 in /home/content/20/10935220/html/engineroom/assets/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 160 in /home/content/20/10935220/html/engineroom/assets/src/Html2Text.php on line 40

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 166 in /home/content/20/10935220/html/engineroom/assets/src/Html2Text.php on line 40

**Comment by twogood** [comment]
If you have invalid HTML I recommend running it through [Tidy](http://php.net/manual/en/book.tidy.php) first.
