### ISSUE TITLE
Add option to discard links

### ISSUE THREAD

**Issue by rif** [soundasleep/html2text#21]
I am using your lib to extract text from html pages to be used as search data. The links, especially the urls are not useful. Can you add an option to discard them?

Thanks a lot!

**Comment by soundasleep** [comment]
Can you not sanitise your input with just replacing e.g.

```
$html = preg_replace('/href="[^"]+"/im', "", $html);
```

**Comment by rif** [comment]
I solved it using some other lib that was a better fit for my particul needs. Thank you.

**Comment by soundasleep** [comment]
This has been implemented as part of PR #65, thank you for the suggestion and your patience!
