### ISSUE TITLE
Use images alt attribute

### ISSUE THREAD

**Issue by jsiefer** [soundasleep/html2text#25]
hi, it would be nice if the alt attribute can be taken for images. Some times converting images that are wrapped inside a a-tag return empty text

    [ ](http://www.example.com/)

**Comment by soundasleep** [comment]
I've made this change in the latest 0.3.0 release, thank you! Images will now display alt tags, and links will display alt/title tags of the `<img>` or `<a>`.

**Comment by jsiefer** [comment]
thank you!
