### ISSUE TITLE
Html special chars

### ISSUE THREAD

**Issue by cronos25** [soundasleep/html2text#33]
Html special chars replacing \&nbsp;\&lt;script&gt;alert(1)\&lt;/script\&gt; => \<script\>alert(1)\</script\>

**Comment by cronos25** [comment]
Fixed if I use htmlspecialchars before convert
$html = htmlspecialchars($html);
					
$text = Html2Text\Html2Text::convert($html);

**Comment by soundasleep** [comment]
Hi, is this still an issue? If so, can you submit a pull request with a test that is failing? Thanks.
