### ISSUE TITLE
Add option to disable warnings during conversion

### ISSUE THREAD

**Issue by rmontagud** [soundasleep/html2text#35]
I have an application in production which relies in user input, which means badly authored HTML so i have a lot of warning messages like these

```
[27-Mar-2016 06:26:01] PHP Warning:  DOMDocument::loadHTML(): ID templateBody already defined in Entity, line: 1340 in /var/.../html2text/src/Html2Text.php on line 44
[27-Mar-2016 06:26:01] PHP Warning:  DOMDocument::loadHTML(): ID templateBody already defined in Entity, line: 1367 in /var/../html2text/src/Html2Text.php on line 44
```

Is it possible to add an option dismiss all those warnings without breaking the error handling? I know there's a function to disable libxml2's error handling but I'm not in the mood of discovering I broke something else the hard way

**Comment by jmserra** [comment]
@rmontagud  you could simply tell php to avoid those by adding an '@' at the beggining like so:

`@ $text = Html2Text\Html2Text::convert($html);`

the warnings shouldnt be dissmissed, instead should be corrected to avoid them, but in the meantime you can just dissmiss on your side

**Comment by rmontagud** [comment]
As much as I'd love to fix the problem on my end I'm afraid I can't since i'm using the component to flatten user supplied HTML

**Comment by soundasleep** [comment]
That's a valid use case. I'll look into adding this as an option. If anyone would like to propose a patch (with tests as well) that would be appreciated :)

**Comment by soundasleep** [comment]
This is now possible with https://github.com/soundasleep/html2text/pull/43
