### ISSUE TITLE
undefined entities - with fix

### ISSUE THREAD

**Issue by sopitz** [soundasleep/html2text#40]
It might go into the direction of #35, but it's a little different use case.

I have a mailchimp-email template and they come with weird unsupported entities.

Changing Html2Text.php around line 50 to this fixes it. The text-version of my email looks perfect, it was just throwing ugly exceptions.

```
$doc = new \DOMDocument();
libxml_use_internal_errors(true);
if (!$doc->loadHTML($html)) {
    throw new Html2TextException("Could not load HTML - badly formed?", $html);
}
libxml_clear_errors();
```

BTW: GREAT WORK WITH THIS TOOL!

**Comment by soundasleep** [comment]
I think this is now supported with https://github.com/soundasleep/html2text/pull/43
