### ISSUE TITLE
Namespace better

### ISSUE THREAD

**Issue by mbaynton** [soundasleep/html2text#45]
On your next major release that can introduce breaking changes, you should consider changing the namespace you use. I just tried to set up a script that preferred your DOM-parser based implementation, but falls back to [this regex-based implementation](https://packagist.org/packages/html2text/html2text) if the input could not be parsed. But, you guys are using the exact same namespace and class name.

You should be \SoundAsleep\Html2Text perhaps.

**Comment by travisaustin** [comment]
I just ran into the same exact issue.
