### ISSUE TITLE
No new release for 10 months

### ISSUE THREAD

**Issue by LordAro** [soundasleep/html2text#48]
Sorry to make this an issue, but it's, well, an issue.

This library's still under fairly active development, but the last release was 10 months ago - 19 June. Do you think we could get a new release, so that we can get features like those in #43 without having to target dev-master, which I'd really hate to have to do

**Comment by soundasleep** [comment]
Absolutely agree. I'll publish a new release next week! Thanks for the reminder.

**Comment by soundasleep** [comment]
I've now released 0.5 which is directly off master, please try this out and let me know if this looks good! Thanks for the suggestion :)
