### ISSUE TITLE
Suggest noting the Apache requirement

### ISSUE THREAD

**Issue by neokio** [soundasleep/html2text#55]
On a new server environment, I was getting the error **`Fatal error: Class 'DOMDocument' not found`** until an excessive amount of googling led me to try running (on Ubuntu) `apt-get install php7.1-xml`, after which everything worked.

**Comment by soundasleep** [comment]
That's a good idea. I don't know if it's possible to add this dependency into `composer.json` - that would be a nice solution. I'll add a note to the README.
