### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by edulis8** [soundasleep/html2text#58]
The library is great. Any chance you could license it under MIT or BSD-3-Clause so I can use it at work, where they only let us use libraries licensed under MIT or BSD-3-Clause?

**Comment by soundasleep** [comment]
@bartbutler are you happy for your contributions to be re-released under MIT?

**Comment by bartbutler** [comment]
No objections here!

**Comment by soundasleep** [comment]
Thanks for the quick reply! I've changed the license to MIT and I'll release a new version later today (probably with some other namespace/API changes, so maybe to 1.0).
