### ISSUE TITLE
Breaks on Ascii Characters

### ISSUE THREAD

**Issue by bekabaz** [soundasleep/html2text#6]
My HTML contains a registered symbol &#174; which is breaking the conversion. Any way to fix to allow html entities?

**Comment by somatonic** [comment]
DOMDocument has issues with utf-8 encoded strings. Your class may work well with english text but with other utf-8 chars like umlaute in other languages you get screwed chars. 

I fixed it with 

static function convert($html) {
		$html = static::fixNewlines($html);
		$html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');
...

**Comment by virtualize** [comment]
thanks @somatonic converting non-latin beforehand did the trick for me
````
$html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');
$text = Html2Text\Html2Text::convert($html);
````

**Comment by twogood** [comment]
+1 on this issue!

Thanks @somatonic for the workaround!

**Comment by imagina** [comment]
Thanks for the convert trick! :D!

**Comment by tribulant** [comment]
@somatonic 

Thank you, this resolved it.
It broken German Umlaut characters

**Comment by cronos25** [comment]
I use utf8_decode 

$text = utf8_decode(Html2Text\Html2Text::convert($html));

**Comment by soundasleep** [comment]
Can anyone attach a sample HTML file that is causing these issues? I'd love to fix this or at least write up an official workaround :)

**Comment by twogood** [comment]
Something like this?
[utf8-example.html.txt](https://github.com/soundasleep/html2text/files/191483/utf8-example.html.txt)

**Comment by soundasleep** [comment]
The workaround looks good, it doesn't change the behaviour of any of the other tests. I've merged this in and released 0.3.2 - can anyone test this out and check that it works better?

**Comment by twogood** [comment]
Maybe `convert()` could take an optional `$encoding` parameter that defaults to `'UTF-8'` and is used as the third parameter to `mb_convert_encoding`? So that the application developer can use `mb_detect_encoding` if she wants to, otherwise just specify a known incoding.

**Comment by soundasleep** [comment]
From what I understand, the behaviour in 0.3.3 will now change the encoding from UTF-8 to HTML-ENTITIES *ONLY* if the document encoding is strictly UTF-8 (the `true` parameter to `mb_detect_encoding`). So, if a developer wants to use a different & known encoding, they can do this *before* they pass the string into `#convert()`, by calling `mb_convert_encoding` themselves.

If not - can you provide a use case/test case so I can understand the issue better?

**Comment by twogood** [comment]
Sounds reasonable, thanks!
