### ISSUE TITLE
Using < character as input to html2text

### ISSUE THREAD

**Issue by vsoundar** [soundasleep/html2text#61]
Dear Jevon and Team,
Appreciate your effort in maintaining this library.  We just started using this library and noticed a small issue that you may have already addressed.
Our input HTML text contains valid '<'  characteras a part of the content (not the html tag).  The library DomParser seems to be stripping that out.  Is there a way we can escape that character and send as input to your library

**Comment by soundasleep** [comment]
I imagine what's going on is that your "valid" input HTML text has "<" characters that aren't encoded to "&lt;"? Can you check that you're encoding your HTML special characters correctly?

**Comment by vsoundar** [comment]
Super Thank You for adding support for &lt.  We will check it out.  
Appreciate your help and thanks much...

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 22, 2019 at 4:15 AM, Jevon Wright<notifications@github.com> wrote:   
I imagine what's going on is that your "valid" input HTML text has "<" characters that aren't encoded to "<"? Can you check that you're encoding your HTML special characters correctly?

**Comment by BlackbitNeueMedien** [comment]
Why not support angle brackets? They are perfectly valid HTML according to http://validator.w3.org/check
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
 <head>
  <title>Test</title>
 </head>
 <body>
  <div>This < is a test.</div>
 </body>
</html>
```

**Comment by soundasleep** [comment]
If you can think of a way to support angle brackets in only HTML 4.01 input, please send through a PR :) Alternatively if there is enough demand for this feature, I can look at building it in...

**Comment by vsoundar** [comment]
Based on Jevon's recommendation, we converted < and > characters into &lt and &got before passing text to this library.  Upon return from this library/function, we swap it back to < and > respoctively.
