### ISSUE TITLE
Minimal version of PHP ?

### ISSUE THREAD

**Issue by ttoine** [soundasleep/html2text#71]
Hello, there is no clear information on this repository, nor a link to a doc, that tells what is the minimum version of PHP to run the current version of html2text library.

With PHP releases moving very fast now, this is becoming a very important information. Projects using PHP dependencies must currently handle many libraries dropping PHP 5.x and early PHP 7.x (at least, 7.0). This would be very helpful to share information about this topic for html2text.

(BTW: thanks for the move to MIT ;-) )

**Comment by soundasleep** [comment]
Hello! It's actually specified in the `composer.json`, as `PHP >= 7.0` :) 

Do you think there is a better place for this information to live?
