### ISSUE TITLE
random DOMDocument::loadHTML() error

### ISSUE THREAD

**Issue by st0at** [soundasleep/html2text#72]
Hi,
When I call
`Html2Text::convert($body);`
I randomly get such errors:

`DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 51
line 171
code 2
file vendor/soundasleep/html2text/src/Html2Text.php
ErrorException: DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 52`

`DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 38`

OS version: Ubuntu 18.04.2 LTS
PHP version: php 7.2.19
Symfony version: 2.8.51
soundasleep/html2text version: 1.1.0

**Comment by moon-deer** [comment]
Try this:
`Html2Text::convert($body, ['ignore_errors' => true]);`

From my tests I can see that I still receiving all the text properly as a result

**Comment by bytestream** [comment]
@edgrosvenor this can be closed per @z3r0gravity solution

**Comment by edgrosvenor** [comment]
@bytestream Yes, I believe it can.
