### ISSUE TITLE
Problem decoding certain unicode representations

### ISSUE THREAD

**Issue by rambii** [soundasleep/html2text#84]
I have some user provided content in my application. Sometimes user pass content that is unexpected.

Run the following code to recreate the error.
```
    $content = "lorem:ipsum";
    $textContent = \Soundasleep\Html2Text::convert($content);
```
Note:  the character is not visible here but can be seen when copied into an editor. The character is after the colon ':'.

In the database it is stored as a Tab (https://www.fileformat.info/info/unicode/char/000b/index.htm), but when I output it and convert it it fails with the error: `DOMDocument::loadHTML(): Invalid char in CDATA 0xB in Entity`

Is there a list of unicode characters which are not supported in this way? 
Is there another way to encode them in the right way?

**Comment by edgrosvenor** [comment]
My sense is that this issue is beyond the scope of this package. I can't know whether the right answer is to simply remove these characters or replace them with something else. That would be a decision better left to the application developer.
