### ISSUE TITLE
💀 Dead project?

### ISSUE THREAD

**Issue by BenMorel** [soundasleep/html2text#89]
Hi,

We've been waiting for an upgrade of this package for compatibility with PHP 8 (#88) for a few months, and even though a fix has been proposed in #86 and #87, no response has been received.

In fact, the last commit & the last release date back to Feb 2019, and so does the [last comment activity](https://github.com/soundasleep/html2text/issues/68#issuecomment-466848496) from @soundasleep I could pinpoint from a quick search in the issue tracker, even though you look active on GitHub recently.

**Should we consider this project abandoned and fork it**, @soundasleep? Or do you need help from fellow maintainers? I'm happy to take over the project, but I don't want to if you may be willing to pursue it at some point.

I hope you take no offense, it's open-source and it's OK if you cannot/don't want to maintain the project anymore. But please let us know! Thank you.

**Comment by ErnestStaug** [comment]
I feel it's safe to say it's dead. Please take over as me and other people actively using this.

**Comment by Yrerbal** [comment]
take a look here https://symfony.com/doc/current/mailer.html#text-content

**Comment by BenMorel** [comment]
@Yrerbal Thanks for the pointer!

I gave a try to [league/html-to-markdown](https://github.com/thephpleague/html-to-markdown), used by Symfony Mailer, and it fits the bill for us, so I won't be forking this package after all.

I'll leave this issue open though, if this can help anyone else.

**Comment by soundasleep** [comment]
Hi everyone, I'm sorry there's not been a lot of action on this project recently! I don't have the time to support this project going forward so I'm looking for some maintainers 🙏 see: #91

**Comment by edgrosvenor** [comment]
I've jumped on as a maintainer here and am working through the issues and pull requests now. I will get a release done with the most important udpates very soon.
