### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by soundasleep** [soundasleep/html2text#91]
Hi everyone! I'm no longer a PHP dev and I've run out of capacity to maintain this project, so I'm looking for some maintainers going forward. Alternatively I can archive the project as read-only.

Ideal criteria:
* You have at least one project on GitHub
* You have experience releasing components to Composer

Other than that I'm happy for maintainers to take this project into whatever direction it needs to go! :)

For the future of this project I'd suggest some of the most critical tasks are

- [x] Move CI from travis-ci to Github Actions
- [x] Update to work under PHP 8 e.g. #87

**Comment by edgrosvenor** [comment]
@soundasleep My company uses this package in one of our projects and would love to have it brought up to PHP 8 and maintained going forward. I have some experience maintaining open source packages in the PHP and would be happy to adopt the package or come onboard and maintain it.

**Comment by soundasleep** [comment]
@edgrosvenor Fantastic, that would be great!! Thank you so much. I've sent you an invite. For publishing new packages we should probably organise that offline: support@jevon.org

**Comment by edgrosvenor** [comment]
@soundasleep Great! I've accepted the invitation. I'll send you a quick email and we'll go from there.

**Comment by bytestream** [comment]
@soundasleep we use this @supportpal and I'd be happy to help keep this going from a maintenance perspective

**Comment by BafS** [comment]
@soundasleep we would also be interested, we are using this library and we would gladly participate (we are actually maintaining have a fork https://github.com/ProtonMail/html2text).

**Comment by edgrosvenor** [comment]
@soundasleep I got a start on getting this package up to date this morning, but hit a bit of a blocker with another one of your packages that this one depends on. I've created a PR here. https://github.com/soundasleep/component-tests/pull/2

If you add me as a maintainer there I can keep that one up to date too. @bytestream and @BafS I'd certainly welcome help in getting through the backlog of issues and PRs. Once this is unblocked and can make sure the test suite works across the supported versions, we should be able to get to inbox 0 on this repo very quickly.

**Comment by edgrosvenor** [comment]
@soundasleep If you'd rather not deal with this, I can just point to a fork of the component-test package and go from there. I hate to keep pulling you back into PHPLand.

**Comment by soundasleep** [comment]
I forgot that I added that dependency! 😅 Added you as a maintainer to that project, too. Amazing work, thank you!!

**Comment by edgrosvenor** [comment]
Thank you! That's actually a really cool package. I might use it in a few other things. There are other solutions to those problems, but yours is really simple and lightweight.

**Comment by edgrosvenor** [comment]
@soundasleep I've merged a fix for the PHP8 problem into master as well as a GitHub Actions workflow testing on Ubuntu from PHP 7.4 through 8.1. I have an open PR that removes the travis configuration and replaces the build status badge with the GitHub Actions one. Do you want to shut off Travis for this project before I merge that in? These two items should be enough to do a release to bring the project back to life, which I'll do tomorrow or Monday.

**Comment by soundasleep** [comment]
@edgrosvenor Thanks so much for all the great work you've done over the last two weeks <3 <3 Really awesome work. Thank you.

I think deleting the .travis.yml should be enough to disable the Travis build (which I don't think is happening right now _anyway_)?

If you message/email me your packagist.org username I'll add you as a maintainer and you should be able to push a new release!

**Comment by edgrosvenor** [comment]
@soundasleep I'm `edgrosvenor` on Packagist, but I don't know that it's necessary for you to add me as a maintainer there. I did a release here on GitHub and it was immediately reflected on Packagist and is generally available. So I think we're all set. I'll take good care of this package. Thanks for creating it!
