### ISSUE TITLE
Ability to change number of new lines in output

### ISSUE THREAD

**Issue by bytestream** [soundasleep/html2text#94]
https://github.com/soundasleep/html2text/blob/master/src/Html2Text.php#L298 specifies to output two LF characters per paragraph. Would you accept a PR which allows one to change the number of LF characters that are output?

The use case is similar to the `MsoNormal`, where no margin exists on the paragraphs. For example:

```html
<p>foo</p><p>&nbsp;</p><p>bar</p><p>quz</p>
```

Output:
```
foo

bar
quz
```

**Comment by edgrosvenor** [comment]
@bytestream If you can do it without breaking backward compatibility, I'd definitely be open to it.
