### ISSUE TITLE
PHP8.1, Deprecated: Optional parameter $prevName declared before required parameter $options

### ISSUE THREAD

**Issue by julien-garand** [soundasleep/html2text#97]
Hi, 

Just another deprecation triggered by php8.1…

( ! ) Deprecated: Optional parameter $prevName declared before required parameter $options is implicitly treated as a required parameter in /[...]/soundasleep/html2text/src/Html2Text.php on line 231

Thanks for all

**Comment by owenvoke** [comment]
Looks like this has been fixed since v2.0.0 🤔 (Was resolved [in April 2021](https://github.com/soundasleep/html2text/commit/a6db8df425312abfc38823429ffe2cb80210c947], and released in Jan 2022)
